### ISSUE TITLE
Add `--proxy` option to yt-dlp

### ISSUE THREAD

**Issue by r4nd0mwOrK933** [jim60105/YoutubeSegmentDownloader#5]
Thanks for your lifesaver.👍

When downloading video segments, ffmpeg cannot automatically use the system proxy and return error with `Error number -138 occurred `. Adding `--proxy` to yt-dlp can solve this issue.

**Comment by jim60105** [comment]
`Error number -138 occurred` indicates that you are unable to connect to the target. This simply points out an error with your network, not specifically a proxy error.

From the source code, it can be seen that both [yt-dlp](https://github.com/yt-dlp/yt-dlp/blob/d3d81cc98f554d0adb87d24bfd6fabaaa803944d/yt_dlp/compat/urllib/request.py#L38) and [ffmpeg](https://github.com/FFmpeg/FFmpeg/blob/d5cc9d8dd9eb592f9467a614ef28e6d5c5381e7c/libavformat/tls.c#L108C14-L108C14) use the system proxy. Please confirm your environment.

Or, in those upstream project, raise an issue if they really cannot use the system proxy.

**Comment by r4nd0mwOrK933** [comment]
I've confirmed my environment and tested the process. FFmpeg use the system proxy in [tls.c](https://github.com/FFmpeg/FFmpeg/blob/d5cc9d8dd9eb592f9467a614ef28e6d5c5381e7c/libavformat/tls.c#L108), but doesn't use it in [tcp.c](https://github.com/FFmpeg/FFmpeg/blob/d5cc9d8dd9eb592f9467a614ef28e6d5c5381e7c/libavformat/tcp.c), where the error occured. I don't know if it's a feature or a bug.
![ScreenShot 1](https://github.com/jim60105/YoutubeSegmentDownloader/assets/83849873/e6bf22b1-0721-4808-8468-7cc5cf6e6b41)
![ScreenShot 2](https://github.com/jim60105/YoutubeSegmentDownloader/assets/83849873/bb1dde42-bab8-445a-93c4-38c0f409d427)

**Comment by r4nd0mwOrK933** [comment]
I've confirmed my environment and tested the process. FFmpeg uses the system proxy in [tls.c](https://github.com/FFmpeg/FFmpeg/blob/d5cc9d8dd9eb592f9467a614ef28e6d5c5381e7c/libavformat/tls.c#L108), but doesn't use it in [tcp.c](https://github.com/FFmpeg/FFmpeg/blob/d5cc9d8dd9eb592f9467a614ef28e6d5c5381e7c/libavformat/tcp.c), where the error occurred. I don't know if it's a feature or a bug.
![ScreenShot 1](https://github.com/jim60105/YoutubeSegmentDownloader/assets/83849873/83886a96-0fc8-4f9f-8ec5-982f4ab62bec)
![ScreenShot 2](https://github.com/jim60105/YoutubeSegmentDownloader/assets/83849873/6f8869ee-5ca6-4110-ace4-af9b8ae67b16)
