### ISSUE TITLE
無法更新FFmpeg

### ISSUE THREAD

**Issue by s3840jeff** [jim60105/YoutubeSegmentDownloader#6]
您好，11月底時有在您當初PO YSD的FB文章下留言未果，只好於12月底在您最近的FB文章下留言。

自從11月更新後，我YSD軟體自動更新時，FFmpeg會一直呈現沙漏狀態無法更新(如圖)，重新下載YSD去更新也是一樣。
雖然GIHUB上似乎可以下載FFmpeg，但github的使用介面對一般人真的很難使用，下載到一些原始碼，也不太知道如何手動更新。
就如同這次回報issue使用信件，也是額外申請帳號才能回報給您。

![image](https://github.com/jim60105/YoutubeSegmentDownloader/assets/146618599/2edc8f23-7217-4db0-981e-a6a4a4215d5e)

**Comment by jim60105** [comment]
@s3840jeff 請更新 [v1.10.0](https://github.com/jim60105/YoutubeSegmentDownloader/releases/tag/v1.10.0)

**Comment by s3840jeff** [comment]
太感動了! 神器復活了~ 感謝大佬救援

**Comment by s3840jeff** [comment]
您好，再度叨擾 回報近期使用狀況
近期使用YSD下載影片時，即高機率會程式關閉(直接消失)
如果是抓短片還有機會在程式當機(消失)前下載完成
但我時常需要抓自己實況VOD檔，基本上都數小時起跳，一定會遇到程式當機
偏偏YT能提供的後台下載影片只有720P 30FPS 做後製剪接不好用
只好再次和您回報問題，希望能尋求解方。
