### ISSUE TITLE
下載影片錯誤

### ISSUE THREAD

**Issue by Yeahya0510** [jim60105/YoutubeSegmentDownloader#8]
**作者你好 感謝你製作YoutubeSegmentDownloader 但我在下載影片上似乎遇到了問題
我嘗試過重新下載程式/重新下載依賴元件/下載之前的版本/重開機/也google了很多關於yt-dlp的相關資料但都還是顯示錯誤
不過在嘗試過程中發現在覆寫下載格式中打mp4是可行的,不過畫質很低
(bestvideo[height<=1080]+bestaudio[ext=m4a]也嘗試過 但失敗了)
在今天失敗前曾嘗試過一次YoutubeSegmentDownloader下載大約1分鐘的影片 是成功的
但今天下載1分鐘的也是失敗(不過1~5秒倒是可以)
底下是我複製錯誤的上面幾段的內容(再次感謝您!)** 
size=  145408KiB time=00:07:28.90 bitrate=2653.6kbits/s speed=2.31x     
size=  145920KiB time=00:07:29.85 bitrate=2657.3kbits/s speed=2.31x     
[out#0/mp4 @ 000001fbfeecd140] video:139068KiB audio:7164KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.354320% 
size=  146750KiB time=00:07:30.00 bitrate=2671.5kbits/s speed=2.31x     
 
[download] 100% of  143.31MiB in 00:03:16 at 746.75KiB/s 
[Exec] Executing command: echo outfile: C:\Users\yeahy\AppData\Local\Temp\tmpsyp4lv.mp4 
C:\Users\yeahy\AppData\Local\Temp\tmpsyp4lv.mp4 
outfile: C:\Users\yeahy\AppData\Local\Temp\tmpsyp4lv.mp4 
Video downloaded. 
Start cutting video with FFmpeg... 
FFmpeg arguments: "-sseof -450 -i \"C:\Users\yeahy\AppData\Local\Temp\tmpsyp4lv.mp4\" -map 0:0 -map 0:1 -y -c:v libx264 -preset slow -crf 18 -c:a aac -b:a 192k -pix_fmt yuv420p -movflags +faststart \"C:\Users\yeahy\AppData\Local\Temp\tmp2fdmns.mp4\"" 
ffmpeg version N-116058-g2902ed25b5-20240630 Copyright (c) 2000-2024 the FFmpeg developers 
  built with gcc 14.1.0 (crosstool-NG 1.26.0.93_a87bf7f) 
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs=-lgomp --extra-ldflags=-pthread --extra-ldexeflags= --cc=x86_64-w64-mingw32-gcc --cxx=x86_64-w64-mingw32-g++ --ar=x86_64-w64-mingw32-gcc-ar --ranlib=x86_64-w64-mingw32-gcc-ranlib --nm=x86_64-w64-mingw32-gcc-nm --extra-version=20240630 
  libavutil      59. 27.100 / 59. 27.100 
  libavcodec     61.  9.100 / 61.  9.100 
  libavformat    61.  4.100 / 61.  4.100 
  libavdevice    61.  2.100 / 61.  2.100 
  libavfilter    10.  2.102 / 10.  2.102 
  libswscale      8.  2.100 /  8.  2.100 
  libswresample   5.  2.100 /  5.  2.100 
  libpostproc    58.  2.100 / 58.  2.100 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\yeahy\AppData\Local\Temp\tmpsyp4lv.mp4': 
  Metadata: 
    major_brand     : isom 
    minor_version   : 512 
    compatible_brands: isomiso2avc1mp41 
    encoder         : Lavf61.4.100 
  Duration: 00:07:30.08, start: 0.000000, bitrate: 2671 kb/s 
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2498 kb/s, 60 fps, 60 tbr, 15360 tbn (default) 
      Metadata: 
        handler_name    : ISO Media file produced by Google Inc. 
        vendor_id       : [0][0][0][0] 
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default) 
      Metadata: 
        handler_name    : SoundHandler 
        vendor_id       : [0][0][0][0] 
Stream mapping: 
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264)) 
  Stream #0:1 -> #0:1 (aac (native) -> aac (native)) 
Press [q] to stop, [?] for help 
[libx264 @ 0000010280180dc0] using SAR=1/1 
[libx264 @ 0000010280180dc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 
[libx264 @ 0000010280180dc0] profile High, level 5.0, 4:2:0, 8-bit 
[libx264 @ 0000010280180dc0] 264 - core 164 - H.264/MPEG-4 AVC codec - Copyleft 2003-2024 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=34 lookahead_threads=5 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00 
Output #0, mp4, to 'C:\Users\yeahy\AppData\Local\Temp\tmp2fdmns.mp4': 
  Metadata: 
    major_brand     : isom 
    minor_version   : 512 
    compatible_brands: isomiso2avc1mp41 
    encoder         : Lavf61.4.100 
  Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 15360 tbn (default) 
      Metadata: 
        handler_name    : ISO Media file produced by Google Inc. 
        vendor_id       : [0][0][0][0] 
        encoder         : Lavc61.9.100 libx264 
      Side data: 
        cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A 
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default) 
      Metadata: 
        handler_name    : SoundHandler 
        vendor_id       : [0][0][0][0] 
        encoder         : Lavc61.9.100 aac 
frame=    7 fps=0.0 q=26.0 size=     256KiB time=00:00:00.08 bitrate=25170.5kbits/s dup=1 drop=0 speed=0.163x     
vvvvvvvvvvvvvvvvvvvvv 
ffmpeg version N-116058-g2902ed25b5-20240630 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.1.0 (crosstool-NG 1.26.0.93_a87bf7f)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs=-lgomp --extra-ldflags=-pthread --extra-ldexeflags= --cc=x86_64-w64-mingw32-gcc --cxx=x86_64-w64-mingw32-g++ --ar=x86_64-w64-mingw32-gcc-ar --ranlib=x86_64-w64-mingw32-gcc-ranlib --nm=x86_64-w64-mingw32-gcc-nm --extra-version=20240630
  libavutil      59. 27.100 / 59. 27.100
  libavcodec     61.  9.100 / 61.  9.100
  libavformat    61.  4.100 / 61.  4.100
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\yeahy\AppData\Local\Temp\tmpsyp4lv.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.4.100
  Duration: 00:07:30.08, start: 0.000000, bitrate: 2671 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2498 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
      Metadata:
        handler_name    : ISO Media file produced by Google Inc.
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0000010280180dc0] using SAR=1/1
[libx264 @ 0000010280180dc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000010280180dc0] profile High, level 5.0, 4:2:0, 8-bit
[libx264 @ 0000010280180dc0] 264 - core 164 - H.264/MPEG-4 AVC codec - Copyleft 2003-2024 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=34 lookahead_threads=5 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\yeahy\AppData\Local\Temp\tmp2fdmns.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.4.100
  Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 15360 tbn (default)
      Metadata:
        handler_name    : ISO Media file produced by Google Inc.
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.9.100 libx264
      Side data:
        cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.9.100 aac
frame=    7 fps=0.0 q=26.0 size=     256KiB time=00:00:00.08 bitrate=25170.5kbits/s dup=1 drop=0 speed=0.163x     
^^^^^^^^^^^^^^^^^^^^^ 
Clean up temporary files. 
Process ends. 
The download process completed without success. 
!!!! FAILED !!!! 
Please check the "Log Verbose" checkbox for more details and try again. 
If you're sure you've found a bug, please report it back to me along with the ENTIRE VERBOSE log.

**Comment by jim60105** [comment]
我無法再現，我自己試了兩個影片狀況都是正常
log 後半段只顯示了 ffmpeg 轉檔階段中止，且沒有任何錯誤資訊
請你把完整的 log 貼上來

**Comment by Yeahya0510** [comment]
非常抱歉
這是log(不過我嘗試了很多方法 所以有點多行) 
辛苦您了!
[YoutubeSegmentDownloader20240701.log](https://github.com/user-attachments/files/16068822/YoutubeSegmentDownloader20240701.log)

**Comment by jim60105** [comment]
同個影片相同參數在我這裡是正常的，從 log 看來也不像是 YoutubeSegmentDownloader 的問題，而是 ffmpeg 自己中斷

請換成 ffmpeg 6.1.1 版試一下，這是前一版的最後發佈版本
最新版 7.0 版引入了多執行緒跟一些酷東西，有可能跟你的平台不相容

https://www.gyan.dev/ffmpeg/builds/
![2024-07-02-221357](https://github.com/jim60105/YoutubeSegmentDownloader/assets/16995691/4f474205-d366-4e1a-b2e4-ef65b005e5fc)

這個階段影片轉檔會把 CPU 吃滿，有可能會被判定異常中斷掉
同時注意一下磁碟使用率、防毒軟體之類的其它因素
謝謝
